# Generated by Django 2.1.1 on 2018-09-24 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(-1, 'brak'), (0, 'Pieczywo'), (1, 'Nabiał i jaja'), (2, 'Mięso i ryby'), (3, 'Sypkie'), (4, 'Tłuszcze'), (5, 'Owoce'), (6, 'Warzywa'), (7, 'Słodycze'), (8, 'Dodatki'), (9, 'Zioła i przyprawy'), (10, 'Napoje'), (11, 'Grzyby')], default=-1, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Składnik')),
                ('price', models.FloatField(blank=True, null=True)),
                ('path', models.ImageField(upload_to='ingredient_photo', verbose_name='Zdjęcie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snack_puzzle.Category', verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snack_puzzle.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'brak'), (1, 'śniadanie'), (2, 'drugie śniadanie'), (3, 'obiad'), (4, 'podwieczorek'), (5, 'kolacja')], default=0, verbose_name='Rodzaj posiłku')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Przepis')),
                ('path', models.ImageField(blank=True, null=True, upload_to='recipe_photo', verbose_name='Zdjęcie')),
                ('description', models.TextField(blank=True, verbose_name='Sposób przygotowania')),
                ('url', models.URLField(blank=True, max_length=100, verbose_name='Link')),
                ('time', models.IntegerField(blank=True, help_text='Czas w minutach', null=True, verbose_name='Czas przygotowania')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_modify', models.DateField(auto_now=True)),
                ('ingredient', models.ManyToManyField(through='snack_puzzle.IngredientRecipe', to='snack_puzzle.Ingredient', verbose_name='Składniki')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Rodzaj')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snack_puzzle.Ingredient', verbose_name='Rodzaj składnika')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ManyToManyField(to='snack_puzzle.Recipe', verbose_name='Dania'),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snack_puzzle.Recipe'),
        ),
    ]
