# Generated by Django 2.1.1 on 2018-10-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack_puzzle', '0002_auto_20181002_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Pie', 'Pieczywo'), ('Nab', 'Nabiał i jaja'), ('Mię', 'Mięso'), ('Syp', 'Sypkie'), ('Tłu', 'Tłuszcze'), ('Owo', 'Owoce'), ('Warz', 'Warzywa'), ('Sło', 'Słodycze'), ('Dod', 'Dodatki'), ('Zio', 'Zioła i przyprawy'), ('Nap', 'Napoje'), ('Grz', 'Grzyby'), ('Ryby', 'Ryby')], default='brak', max_length=100, verbose_name='Kategoria'),
        ),
    ]
