# Generated by Django 2.1.1 on 2018-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack_puzzle', '0010_auto_20181004_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='measure',
            field=models.CharField(choices=[('g', 'g'), ('dag', 'dag'), ('szt.', 'szt.'), ('szklan.', 'szklan.'), ('łyż.', 'łyż.'), ('łyżecz.', 'łyżecz.'), ('szczypt.', 'szczypt.'), ('pęcz.', 'pęcz.'), ('opak.', 'opak.'), ('l', 'l')], default='dag', max_length=32, null=True, verbose_name='Miara'),
        ),
    ]
