# Generated by Django 2.1.1 on 2018-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack_puzzle', '0011_auto_20181004_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Czas przygotowania ( w min.)'),
        ),
    ]
