# Generated by Django 2.1.1 on 2018-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snack_puzzle', '0013_auto_20181020_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True, max_length=100, verbose_name='Link do przepisu'),
        ),
    ]
